### ISSUE TITLE
Reduce size of Cottage category block

### ISSUE THREAD

**Issue by noush-h2o** [boscnegre-vacances/boscnegre-vacances.github.io#10]
Please reduce the blocs on this page please
http://boscnegre.netlify.com/gites-indiv-4-6/ 
Leave a margin on both sides

**Comment by noush-h2o** [comment]
Can you reduce a bit more ?

**Comment by xuopled** [comment]
I don't understand what you mean

**Comment by noush-h2o** [comment]
What I mean is that on these pages : http://boscnegre.netlify.com/gites-mitoyen-5-7/
The bloc of the gite don't have a margin. It takes the whole screen om my mac. Can you reduce a bit so there is a margin and it doens't take the whole screen please ? I hope I explain better this time.
Maybe you disagree with me for aestitic reasons.

**Comment by xuopled** [comment]
Ok I reduced the block. But imho it's not homogeneous with the others pages.

**Comment by noush-h2o** [comment]
So you think we shouldn't do it ? 
As I said above, you may desagree for aestitic reasons, so we can discuse this subject face to face.
