### ISSUE TITLE
Handle link to SecureHoliday

### ISSUE THREAD

**Issue by noush-h2o** [boscnegre-vacances/boscnegre-vacances.github.io#13]
On the page FR_cottages, I need a metadata with a link to refer to SecureHoliday. I did you integrate the data in your code ? Please tell me the metadata I can add in Siteleaf.
Exemple link from bergerie to secure holiday is : https://premium.secureholiday.net/fr/14230/product.popup?idProduct=63380

It's the idProduct number that will change.

Thank you.

**Comment by xuopled** [comment]
Please fullfill the `ctoutvertId` metadata
