### ISSUE TITLE
Front menu NL

### ISSUE THREAD

**Issue by noush-h2o** [boscnegre-vacances/boscnegre-vacances.github.io#14]
En NL, le menu haut de page n'a pas le même design qu'en NL. Des petits traits blanc dépassent du menu en haut.
http://boscnegre.netlify.com/nl/

**Comment by xuopled** [comment]
"Volg de Bosc negre" is too long so there are two lines. We saw together the nav is split in 8 parts so you need to add a shorter title. Is it possible or I need to find an other solution ?

**Comment by noush-h2o** [comment]
Ok yes no problem. Then the problem shouldn't show anymore because I hid the page "volg de bosc negre"

**Comment by noush-h2o** [comment]
The fonctionnality "hidden" doesn't work correctly. The boscnegre-vacances.github.io/nl_pages/volg-de-bosc-negre.html page is tagged as hidden in the CMS

**Comment by xuopled** [comment]
You should not use the `Siteleaf` visible filter. If you don't want to display a page, pleade add a `is_visible` metadata to the page. I added one to `Volg de Bosc negre` page
