### ISSUE TITLE
Region page

### ISSUE THREAD

**Issue by noush-h2o** [boscnegre-vacances/boscnegre-vacances.github.io#15]
In NL, the region page doesn't have the correct display; the H2 isn't something I've written in the CMS.
boscnegre-vacances.github.io/nl_pages/regio.html  

The layout is  region like in French. 
Thanks for looking

**Comment by noush-h2o** [comment]
No it's ok now. In NL there wasn't a metafield "coordinates". now I've added one and the map + texts shows.
HOWEVER, one extra question : where do you get the H2 from ?

**Comment by xuopled** [comment]
For now, h2 titles are not editable in CMS

**Comment by noush-h2o** [comment]
Ok.
