### ISSUE TITLE
# in heading 2

### ISSUE THREAD

**Issue by noush-h2o** [boscnegre-vacances/boscnegre-vacances.github.io#16]
The H2 in the text have an # before the text. This generates an URL like http://boscnegre.netlify.com/groupes/vacances-sportives/#les-randonn%C3%A9es-du-p%C3%A9rigord-noir

This example is on the region page. Please delete the #

**Comment by noush-h2o** [comment]
FOr the seminaire page, the heading 2 aren't developed. http://boscnegre.netlify.com/seminaires/
The double # stays in front of the sentence

**Comment by xuopled** [comment]
I removed automatic anchors

**Comment by noush-h2o** [comment]
Now the balises are in the text 

<h2>23 gîtes disponibles pour vous héberger durant le séminaire</h2> <p>23 gîtes de deux chambres sont à votre disposition. Ceux-ci ont chacun une chambre double et une chambre individuelle (avec trois couchages), ainsi qu’une salle de bain/salle d’eau, toilettes, cuisine et salon</p>

**Comment by xuopled** [comment]
I don't understand what you mean. I in siteleaf, you select "Titre 2", you will have an `h2`. And so on

**Comment by noush-h2o** [comment]
Please take a look at the seminaire page.
you will see a balise H2 in the text. The CSS isn't taken into account.
http://boscnegre.netlify.com/seminaires/

**Comment by xuopled** [comment]
Ok I understood. It should be ok now
