### ISSUE TITLE
Double category

### ISSUE THREAD

**Issue by noush-h2o** [boscnegre-vacances/boscnegre-vacances.github.io#17]
There is a category cottage and cottageS is the layout. Can you delete the cottageS ? I think the one we should use to display the cottage blocs is the layout cottage.

**Comment by xuopled** [comment]
Page with the layout `Cottages` is page listing cottages categories.
Page with the layout `CottagesCategory` is page listing cottages from a specific category.

But you are right. It was not an explicit name. So I renamed the `Cottages` layout to `CottagesCategories`

**Comment by noush-h2o** [comment]
That's not what I said. I said there is a layout Cottage with a S and one without.
thus COTTAGE and COTTAGES.

**Comment by xuopled** [comment]
Yes I know. It has to be like that. Cottages need to have a `Cottage` layout

**Comment by noush-h2o** [comment]
I see three layouts : cottages / cottageCategory / cottageCategories
What's the difference ?

CottagesCategory is page listing cottages from a specific category.
Cottages is page listing cottages categories.

ANd cottageCategorie?

**Comment by xuopled** [comment]
`CottagesCategories` => categories
`CottagesCategory` => cottages from a specific category
`Cottage` => one cottage (There is no cottage page but it is usefull for me to know that is a Cottage document"
