### ISSUE TITLE
/ at the end of the URL

### ISSUE THREAD

**Issue by noush-h2o** [boscnegre-vacances/boscnegre-vacances.github.io#18]
There is / after each URL even if I didn't wrote it in the route. Can you delete the extra / please ?
Example : http://boscnegre.netlify.com/activites/sport/

**Comment by xuopled** [comment]
It's not possible with the tool I use. But please read https://webmasters.googleblog.com/2010/04/to-slash-or-not-to-slash.html

If you go to  http://boscnegre.netlify.com/activites/sport you will be redirected to  http://boscnegre.netlify.com/activites/sport/ 

So we are good for seo

**Comment by noush-h2o** [comment]
Ok then we can leave / and redirect the sport to sport/ but sport/ is the official URL. The one that has to be communicated in the sitemap
