### ISSUE TITLE
Total caracters in text for cottage

### ISSUE THREAD

**Issue by noush-h2o** [boscnegre-vacances/boscnegre-vacances.github.io#19]
On this page, the text for each cottage is cut because it's too long.
http://boscnegre.netlify.com/gites-mitoyen-5-7/ 

Please increase the display of the text to show more caracters.
Also, tell me the limit of caracters to that we don't write too much in the CMS

**Comment by xuopled** [comment]
I deleted all cottages pages and add cottages to categories pages
