### ISSUE TITLE
Carroussel missing

### ISSUE THREAD

**Issue by noush-h2o** [boscnegre-vacances/boscnegre-vacances.github.io#20]
The carroussels are missing on the page. Like for example on this page : http://boscnegre.netlify.com/groupes/vacances-sportives/ 
https://manage.siteleaf.com/documents/5845cfa4ed2f164799df3567/edit 

I added the pictures on tuesday evening and they were displayed correclty.

**Comment by xuopled** [comment]
I never add this feature. We never talked about photos on Group pages.
But ok I added it now

**Comment by noush-h2o** [comment]
But that's strange because I've seen it online ! It has been developed. But sudently is was gone !
