### ISSUE TITLE
€ Sign not displayed

### ISSUE THREAD

**Issue by noush-h2o** [boscnegre-vacances/boscnegre-vacances.github.io#21]
The € sign is not taken into account on the seminaire page at the bottom of the page.

In the metafield priceExamples > price, I've written : 112€ HT par personne and online is see Nan par personne http://boscnegre.netlify.com/seminaires/

**Comment by xuopled** [comment]
`NaN` mean `Not a number`. So you enter a string instead of a number

**Comment by noush-h2o** [comment]
I wrote 112€ per person. Can you add a metafield for € HT then ?

**Comment by xuopled** [comment]
I remove all formatting. So please update texts. You can write everything you want and specify "per person" or not
