### ISSUE TITLE
Hard links in dutch

### ISSUE THREAD

**Issue by noush-h2o** [boscnegre-vacances/boscnegre-vacances.github.io#23]
Please change the hard links on the NL page : 

footer : camping2be : https://nl.camping2be.com/france/lacapelle-biron/klantenbeoordelingen-village-de-vacances-bosc-negre 
Tripadvisor : https://www.tripadvisor.nl/Hotel_Review-g1856959-d2058207-Reviews-Village_de_vacances_Bosc_Negre-Lacapelle_Biron_Lot_et_Garonne_Nouvelle_Aquitaine.html

**Comment by xuopled** [comment]
I fixed it
