### ISSUE TITLE
Priority 1 - Link on home page

### ISSUE THREAD

**Issue by noush-h2o** [boscnegre-vacances/boscnegre-vacances.github.io#33]
On the bloc offers, please add a meta below cover and text to put the URL we want to link to. Thanks

FR: https://boscnegrevacancesfr.premium.secureholiday.net/fr/14230/weekprices
NL : https://boscnegrevacancesfr.premium.secureholiday.net/nl/14230/weekprices

**Comment by xuopled** [comment]
Done
