### ISSUE TITLE
no H1 on home page

### ISSUE THREAD

**Issue by noush-h2o** [boscnegre-vacances/boscnegre-vacances.github.io#38]
There is no H1 on the home page whereas there are five H2. This is not logical from a SEO point of view. Can we add the H1 on the main picture in the header like on other pages ? which would say for instance : Bienvenue au Village de Vacances du Bosc Nègre.
This has to be a meta field in the CMS.

**Comment by xuopled** [comment]
It should be ok. Please update title in the CMS
