### ISSUE TITLE
Priority 4 - External link

### ISSUE THREAD

**Issue by noush-h2o** [boscnegre-vacances/boscnegre-vacances.github.io#41]
Can you make sure that external link open a new tab please ?

If we send customers to an external link, it has to open a new window otherwise we loose customers. 
https://www.boscnegre-vacances.com/region/

**Comment by xuopled** [comment]
Done. But I needed to put html links directly in the markown file. So You can't do with the CMS WYSIWYG. Don't edit the page or maybe Siteleaf will transform my links

**Comment by noush-h2o** [comment]
How do we deal with future external link ?

**Comment by xuopled** [comment]
Ok I found a way and I add `target="_blank"` and `rel="nofollow noopener noreferrer"` automatically on external links from cms
