### ISSUE TITLE
Priority 2 - Add zoover link

### ISSUE THREAD

**Issue by noush-h2o** [boscnegre-vacances/boscnegre-vacances.github.io#43]
Please add a zoover link in the footer and a picture.
Tell me when y deal this, I will give you the script.

**Comment by xuopled** [comment]
I did

**Comment by noush-h2o** [comment]
<div class="zvr-widget zvr-widget--awards">
            <div class="zvr-widget-container" id="zoover-widget-awards-container">
            <div class="acco-name section"><a href="http://www.zoover.nl/frankrijk/aquitaine/lacapelle-biron/hameau-de-bosc-negre/vakantiepark" target="_blank">Hameau de Bosc N&egrave;gre****</a></div>
            <div class="section logo-container"><object class="zvr-logo" id="zvr-award-logo" data="http://www.zoover.com/Shared/images2/zoover-awards/award_winner.svg" type="image/svg+xml"><img id="zvr-award-logo-ie8" src="http://www.zoover.com/Shared/images2/zoover-awards/award_winner.png" alt="" /></object><span id="zvr-award-year" class="award_winner">2015</span><span id="zvr-award-award">award winner gold</span></div>
            <div class="widget-footer">
            <div class="align-center" id="widgets-content-158987-2-a">&nbsp;</div>
            </div>
            </div>
            </div>
            <table width="100%" border="0" align="center" cellpadding="1" cellspacing="1">
                <tbody>
                    <tr>
                        <script type="text/javascript">var logoLink = document.getElementById("widget-logo-158987");logoLink.href = "";</script><script type="text/javascript" src="http://www.zoover.com/widgets/loadwidgetdynamiccontent.aspx?entid=158987&entlvl=accommodation&widgetType=2&position=widgets-content-158987-2-a"></script>                         <script type="text/javascript">var fileref = document.createElement("link");fileref.setAttribute("rel", "stylesheet");fileref.setAttribute("type", "text/css");fileref.setAttribute("href", "http://www.zoover.com/Shared/Css/zoover-widgets.v2.css");var head = document.getElementsByTagName('head')[0];var headerContent = head.innerHTML;if(headerContent.indexOf("http://www.zoover.com/Shared/Css/zoover-widgets.v2.css") == -1){head.appendChild(fileref);}</script>
                        <td style="text-align: center;" width="246"><a target="_blank"

**Comment by noush-h2o** [comment]
can you place this script so we see the logo gold award winner ?

**Comment by xuopled** [comment]
I updated the logo

**Comment by noush-h2o** [comment]
you can't add 2015 award winner gold underneath ?
