### ISSUE TITLE
change google analytics

### ISSUE THREAD

**Issue by noush-h2o** [boscnegre-vacances/boscnegre-vacances.github.io#45]
Can you edit the Google Analytics script please ?
Instead of : 
<script>
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','https://www.google-analytics.com/analytics.js','ga');

  ga('create', 'UA-89979431-1', 'auto');
  ga('send', 'pageview');

</script>

USE : 
<script>
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','https://www.google-analytics.com/analytics.js','ga');

ga('create', 'UA-89979431-1', 'auto'{'allowLinker': true});
ga('require', 'linker');
ga('linker:autoLink', ['premium.secureholiday.net', 'www.secureholiday.net']);
ga('send', 'pageview');

</script>

**Comment by xuopled** [comment]
Please check

**Comment by noush-h2o** [comment]
I can't see i

**Comment by xuopled** [comment]
You will not see this exact script. I use it an other way

**Comment by xuopled** [comment]
Please verify in the google console

**Comment by noush-h2o** [comment]
I think it's ok
