### ISSUE TITLE
new upload photo don't show

### ISSUE THREAD

**Issue by noush-h2o** [boscnegre-vacances/boscnegre-vacances.github.io#5]
I just uploaded a new picture on this page : http://boscnegre.netlify.com/activites/piscine/ 
It's didn't upload. 
It's not a deploiement problem as the rest of the text I changed on that page has been updated correctly.

**Comment by noush-h2o** [comment]
I still have the same issue. I just uploaded a new pictures on this page : http://boscnegre.netlify.com/activites/animations/

**Comment by xuopled** [comment]
Please name images correctly. A correct filename does't have spaces and specials chars like accents
