### ISSUE TITLE
Collection issue

### ISSUE THREAD

**Issue by noush-h2o** [boscnegre-vacances/boscnegre-vacances.github.io#6]
In the collection "service", I selected only 4 documents. However, I keep seeing the extra service which isn't in SiteLeaf : "evenemtents".

**Comment by xuopled** [comment]
You did not provide the route so the `evenemtents` appears in `fr` with route `http://boscnegre.netlify.com/_nl_services/animations/`

**Comment by noush-h2o** [comment]
evenements shouldn't appear online as I deleted it from the collection FR_services
