### ISSUE TITLE
Extra document won't show

### ISSUE THREAD

**Issue by noush-h2o** [boscnegre-vacances/boscnegre-vacances.github.io#7]
I've added a 5th document in the collection FR_groups but it doesn't show only. 
When I select the responsive version, I use the arrows to see if there's isn't a 5th document and I still don't see it.
If I directly select the route I see the page http://boscnegre.netlify.com/sport/. Which means the page exists.

**Comment by xuopled** [comment]
Where do you look for it ?

I can see it in homepage:

![capture d ecran 2016-12-07 09 18 46](https://cloud.githubusercontent.com/assets/2683300/20959965/2df3987a-bc5e-11e6-9430-70eee61ac333.png)

**Comment by noush-h2o** [comment]
It's in the collection GROUPS and not services

**Comment by xuopled** [comment]
don't you use the same route ?

**Comment by noush-h2o** [comment]
It's a dedicated page about sport for groups. It belongs to the collection Groups and not services. There are two routes for sports. One belonging to services activites/sport and one for groupes /sport

**Comment by xuopled** [comment]
I saw you change the route. Is the problem still here ?

**Comment by noush-h2o** [comment]
Yes it's still there. The category doesn't show in the carrousel GROUPS neither in the menu

**Comment by xuopled** [comment]
you did not set the layout to `Group`
