### ISSUE TITLE
Categories selecter

### ISSUE THREAD

**Issue by noush-h2o** [boscnegre-vacances/boscnegre-vacances.github.io#8]
When I want to associate a cottage to a cottage_category there is a bug. 
Please force me to select in a list of cottage_category.

**Comment by xuopled** [comment]
I did a fix. You need to check

**Comment by noush-h2o** [comment]
I selected the "bergerie" to cottage 7/9 persons and it doesn't show online.
http://boscnegre.netlify.com/gites-mit-7-9/

**Comment by noush-h2o** [comment]
Can you recheck this issue ? It's not fixed.
http://boscnegre.netlify.com/gites-indiv-5-7/ 
There is nothing on this page

**Comment by xuopled** [comment]
I deleted all cottages pages and add cottages to categories pages
