### ISSUE TITLE
Link color on Region page

### ISSUE THREAD

**Issue by noush-h2o** [boscnegre-vacances/boscnegre-vacances.github.io#9]
Please show the links in a different color.
http://boscnegre.netlify.com/region/ there is link at the bottom of the text

**Comment by xuopled** [comment]
Link will be green now

**Comment by noush-h2o** [comment]
This issue is not only on the region page. It's everywhere where there is a link
http://boscnegre.netlify.com/nl/contact/ 
The link is on the 3rd line : online boeken

**Comment by xuopled** [comment]
Done
